### ISSUE TITLE
CLI force user to define some flag when updating an existing service

### ISSUE THREAD

**Issue by Isilud** [squarescale/squarescale-cli#135]
You cannot update a service without specifying the number of instances or at least one of runCmdArg, noRunCmdArg, limitCPUArg and limitMemoryArg. The number of instance default to -1.
We should check sqsc/web and investigate if the default value is handled and how it is linked to the others variables.

**Comment by obourdon** [comment]
This was indeed a bug be will be removed the in last version

**Comment by obourdon** [comment]
Fixed in [https://github.com/squarescale/squarescale-cli/pull/153](https://github.com/squarescale/squarescale-cli/pull/153)
